#!/bin/sh
# run lint checker (flake8) script in the background
echo "Look for linting output in .git/hooks/.flake8_lint.log"
nohup ./.git/hooks/delint_working_dir 2>&1  | tee .git/hooks/.delint_working_dir.log &
