# Config file for automatic testing at travis-ci.org

sudo: false
language: python

addons:
  apt:
    packages:
    - build-essential
    - libblas-dev
    - liblapack-dev
    - libatlas-dev
    - gfortran
    - abiword
    - libpng12-dev
    - libfreetype6-dev

python:
  - "2.7"

cache:
  apt: true
  directories:
    - $HOME/.pip-cache/
    - $HOME/virtualenv/python2.7
    - $HOME/virtualenv/python2.7.9
    - $HOME/nltk_data
    - $HOME/.db-cache

branches:
  except:
    - /notest/

before_install:
  - pip install --upgrade pip
  - pip install requests matplotlib

install:
  - travis_wait 60 pip install -q -r requirements.txt
#  - python -c "import gensim; print(gensim.__version__)"
  - python -m nltk.downloader -d $HOME/nltk_data punkt
  - python -m nltk.downloader -d $HOME/nltk_data stopwords

script:
  - coverage run setup.py test -v 3
  - coverage report
#  - flake8 --config .flake8.cfg .
#  - python $HOME/copenhagen/travis/future_verification.py django
#  - python $HOME/copenhagen/travis/check_py3k.py .

notifications:
  email: false
  slack: totalgood:Fsy4rZmIWs8NnzhCM7HeTvWh
  on_success: change
  on_start: never
  on_failure: always
